scrape_configs:
  - job_name: 'CleanArch WebFlux API'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['10.5.0.2:8080']
        labels:
          application: 'webfluxapi'