spring:
  application:
    name: webfluxapi
  r2dbc:
    url: r2dbc:h2:mem:///userdb
    username:
    password:
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: 123

  data:
    r2dbc:
      repositories:
        enabled: true

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

database:
  h2:
    active: ${H2_ACTIVE}

http:
  base-uri: ${BASE_URI_WIREMOCK}

logging:
  level:
    io.r2dbc.h2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus